### PR TITLE
fix(git-sidecar): support branch names and tags

### LINKED ISSUE #228: vcs-sidecar fails when passed a branch name and commit hash
I encountered these failures when trying to build a branch with brigade.

## Branch Name
I noticed that the vcs-sidecar had a familiar exception (128) and that the whole job failed because of this. Here's the output from that container:

```console
kubectl logs do-nothing-1513714578597-test-ecr --namespace operations vcs-sidecar
+ : /src
+ : git@github.com:blimmer/k8s_deploy_demo.git
+ : test-ecr-pull
+ git clone --depth=50 git@github.com:blimmer/k8s_deploy_demo.git /src
Cloning into '/src'...
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
+ cd /src
+ git fetch origin test-ecr-pull
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
From github.com:blimmer/k8s_deploy_demo
 * branch            test-ecr-pull -> FETCH_HEAD
+ git checkout -qf FETCH_HEAD
+ git reset --hard -q test-ecr-pull
fatal: ambiguous argument 'test-ecr-pull': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

This problem occurs locally for me, too.

The solution is that, in the case of branches, you need to pass the `--branch=<branch-name>` parameter along with the `--depth` parameter. This is because the `--depth` parameter in `git` implies `--single-branch`, as well ([docs](https://git-scm.com/docs/git-clone#git-clone---depthltdepthgt))

The tricky part is that the `--branch` parameter can only accept named tags and branches, and cannot take a commit hash, so switching logic will need to be added for this case.

## Commit Hash
This one exited with exit code (1).

```console
+ : /src
+ : git@github.com:blimmer/k8s_deploy_demo.git
+ : 1353a9d889ae7ec6c53304c2abe893aa0aaee5d1
+ git clone --depth=50 git@github.com:blimmer/k8s_deploy_demo.git /src
Cloning into '/src'...
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
+ cd /src
+ git fetch origin 1353a9d889ae7ec6c53304c2abe893aa0aaee5d1
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
error: Server does not allow request for unadvertised object 1353a9d889ae7ec6c53304c2abe893aa0aaee5d1
```

Again, this is because of the depth issue. That command would work if `1353a9d889ae7ec6c53304c2abe893aa0aaee5d1` were the tip of the branch but, in this case it wasn't.

### PR DESCRIPTION
**Pull request by adamreese**
Lookup revision in remote repository to get SHA

fixes #228

### CODE REVIEW

File: git-sidecar/rootfs/clone.sh [hunk 1]
```diff
@@ -6,6 +6,10 @@ set -x
 : "${VCS_REPO:?}"
 : "${VCS_REVISION:?}"
 
+if sha=$(git ls-remote --exit-code "${VCS_REPO}" "${VCS_REVISION}" | cut -f1); then
```
Comment (mumoshu) [inline git-sidecar/rootfs/clone.sh]: Nit but shouldn't VCS_REVISION be renamed to e.g. `VCS_REF` as it doesn't stand only for REVISION now?

Comment (adamreese) [reply git-sidecar/rootfs/clone.sh]: I have another PR that fixing the naming

**Comment by blimmer** [comment]
Thank you @adamreese !
