### PR TITLE
fix(brig): wait for pod to start

### LINKED ISSUE #162: controller doesn't wait long enough for brigade-worker pod to start
**STR:**
- on a new cluster with brigade installed, run `brig run -f brigade.js deis/empty-testbed` per README

**EXPECTED:**
- I see detailed output of running your brigade.js script's exec hook

**ACTUAL:**
The controller doesn't appear to wait long enough for the worker pods to startup. On the first runs this would cause the error below; after the nodes had cached Docker images I wasn't able to reproduce.
```
brig run -f brigade.js deis/empty-testbed
Started brigade-worker-01bzgeb05qcyw37wqdb0yzc350-master
Error: container "brigade-runner" in pod "brigade-worker-01bzgeb05qcyw37wqdb0yzc350-master" is waiting to start: ContainerCreating
Usage:
  brig run PROJECT [flags]
```

### PR DESCRIPTION
**Pull request by technosophos**
This makes Brig much smarter about waiting for a pod to start before
querying the log. It watches the pod stream for the build to go into
Running or Succeeded state. Then it goes on to the logs.

Closes #162

### CODE REVIEW

File: brig/cmd/brig/commands/run.go [hunk 1]
```diff
@@ -125,13 +127,58 @@ func (a *scriptRunner) send(projectName string, data []byte) error {
...
+				return fmt.Errorf("Worker %s was just deleted unexpectedly.", buildID)
+			case "ADDED", "MODIFIED":
+				pod := e.Object.(*v1.Pod)
+				switch pod.Status.Phase {
+				// Unhandled cases are Unknown and Pending, both of which should
+				// cause the loop to spin.
+				case "Running", "Succeeded":
+					return nil
+				case "Failed":
+					return fmt.Errorf("Pod failed to schedule: %s", pod.Status.Reason)
```
Comment (seanknox) [inline brig/cmd/brig/commands/run.go]: LGTM pending calling `req.Stop()` in `case e := <-res`  as discussed.
